"""Evaluate a saved model on its held-out test set and write a report.

Usage:
    python -m src.evaluate
"""
import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)

from src.config import (
    DEFAULT_MODEL_PATH,
    DEFAULT_REPORT_PATH,
    DEFAULT_TEST_DATA_PATH,
    DOCUMENTED_RESULTS,
    PROJECT_ROOT,
)
from src.data_preprocessing import load_data, split_features_target
from src.model_io import load_model


def evaluate_model(bundle, X_test, y_test):
    """Compute classification metrics for the saved pipeline on (X_test, y_test).

    Binary targets: precision/recall/F1 use the bundle's positive label.
    Multiclass targets: precision/recall/F1 are macro-averaged.
    ROC-AUC is None if it cannot be computed (e.g. only one class in y_test).
    """
    pipeline = bundle["pipeline"]
    classes = list(pipeline.classes_)
    y_pred = pipeline.predict(X_test)
    y_proba = pipeline.predict_proba(X_test)

    metrics = {
        "n_test": int(len(y_test)),
        "classes": [c.item() if hasattr(c, "item") else c for c in classes],
        "accuracy": float(accuracy_score(y_test, y_pred)),
    }

    if len(classes) == 2:
        positive = bundle["positive_label"]
        pos_index = classes.index(positive)
        metrics["average"] = f"binary (positive label = {positive})"
        metrics["positive_label"] = positive.item() if hasattr(positive, "item") else positive
        kwargs = {"average": "binary", "pos_label": positive, "zero_division": 0}
        try:
            metrics["roc_auc"] = float(
                roc_auc_score((np.asarray(y_test) == positive).astype(int), y_proba[:, pos_index])
            )
        except ValueError:
            metrics["roc_auc"] = None
    else:
        metrics["average"] = "macro"
        kwargs = {"average": "macro", "zero_division": 0}
        try:
            metrics["roc_auc"] = float(
                roc_auc_score(y_test, y_proba, multi_class="ovr", average="macro", labels=classes)
            )
        except ValueError:
            metrics["roc_auc"] = None

    metrics["precision"] = float(precision_score(y_test, y_pred, **kwargs))
    metrics["recall"] = float(recall_score(y_test, y_pred, **kwargs))
    metrics["f1"] = float(f1_score(y_test, y_pred, **kwargs))
    metrics["confusion_matrix"] = confusion_matrix(y_test, y_pred, labels=classes).tolist()
    return metrics


def compare_with_documented(metrics):
    """Compare current metrics with the documented ones at the documented precision.

    Returns None for non-binary targets (the documented numbers are not comparable).
    """
    if len(metrics["classes"]) != 2 or metrics.get("roc_auc") is None:
        return None
    return {
        "accuracy": round(metrics["accuracy"] * 100, 2) == round(DOCUMENTED_RESULTS["accuracy"] * 100, 2),
        "recall": round(metrics["recall"] * 100, 2) == round(DOCUMENTED_RESULTS["recall"] * 100, 2),
        "roc_auc": round(metrics["roc_auc"], 4) == round(DOCUMENTED_RESULTS["roc_auc"], 4),
    }


def _display_path(path):
    """Show paths relative to the project root when possible."""
    try:
        return str(Path(path).resolve().relative_to(PROJECT_ROOT))
    except ValueError:
        return str(path)


def _fmt(value):
    return "n/a" if value is None else f"{value:.4f} ({value * 100:.2f}%)"


def build_report(metrics, bundle, model_path, test_data_path, dataset_label):
    comparison = compare_with_documented(metrics)
    if comparison is None:
        verdict = "Not comparable (documented results are for a binary task with a computable ROC-AUC)."
    elif all(comparison.values()):
        verdict = "All three documented metrics are reproduced by this run (to the documented precision)."
    else:
        mismatched = ", ".join(k for k, ok in comparison.items() if not ok)
        verdict = f"NOT reproduced by this run. Metrics that differ from the documented values: {mismatched}."

    classes = metrics["classes"]
    header = "| Actual \\ Predicted | " + " | ".join(str(c) for c in classes) + " |"
    divider = "|---|" + "---|" * len(classes)
    rows = [
        f"| **{cls}** | " + " | ".join(str(v) for v in row) + " |"
        for cls, row in zip(classes, metrics["confusion_matrix"])
    ]

    lines = [
        "# Evaluation Results",
        "",
        f"_Generated by `python -m src.evaluate` on {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}._",
        "",
        f"- **Dataset:** {dataset_label}",
        f"- **Training data file:** `{_display_path(bundle.get('training_data_path', 'unknown'))}`",
        f"- **Model file:** `{_display_path(model_path)}`",
        f"- **Held-out test file:** `{_display_path(test_data_path)}` ({metrics['n_test']:,} rows)",
        f"- **Precision/Recall/F1 averaging:** {metrics['average']}",
        "",
        "## Documented project result (author-supplied, NOT produced by this run)",
        "",
        "| Metric | Documented value |",
        "|---|---|",
        f"| Accuracy | {DOCUMENTED_RESULTS['accuracy'] * 100:.2f}% |",
        f"| Recall | {DOCUMENTED_RESULTS['recall'] * 100:.2f}% |",
        f"| ROC-AUC | {DOCUMENTED_RESULTS['roc_auc']:.4f} |",
        "",
        "## Current reproducible result (computed by this run)",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Accuracy | {_fmt(metrics['accuracy'])} |",
        f"| Precision | {_fmt(metrics['precision'])} |",
        f"| Recall | {_fmt(metrics['recall'])} |",
        f"| F1-score | {_fmt(metrics['f1'])} |",
        f"| ROC-AUC | {_fmt(metrics['roc_auc'])} |",
        "",
        "## Comparison with documented result",
        "",
        verdict,
        "",
        "## Confusion matrix",
        "",
        header,
        divider,
        *rows,
        "",
    ]
    return "\n".join(lines)


def run_evaluation(
    model_path=DEFAULT_MODEL_PATH,
    test_data_path=DEFAULT_TEST_DATA_PATH,
    report_path=DEFAULT_REPORT_PATH,
    dataset_label="User-supplied dataset",
):
    """Load model + test set, compute metrics, write markdown and JSON reports."""
    bundle = load_model(model_path)
    test_df = load_data(test_data_path)
    X_test, y_test = split_features_target(test_df, bundle["target_column"])
    X_test = X_test[bundle["feature_columns"]]

    metrics = evaluate_model(bundle, X_test, y_test)

    report_path = Path(report_path)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(build_report(metrics, bundle, model_path, test_data_path, dataset_label))
    report_path.with_suffix(".json").write_text(json.dumps(metrics, indent=2))

    print(f"Accuracy : {_fmt(metrics['accuracy'])}")
    print(f"Precision: {_fmt(metrics['precision'])}")
    print(f"Recall   : {_fmt(metrics['recall'])}")
    print(f"F1-score : {_fmt(metrics['f1'])}")
    print(f"ROC-AUC  : {_fmt(metrics['roc_auc'])}")
    print(f"Report written to {_display_path(report_path)}")
    return metrics


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description="Evaluate the saved model on its test set.")
    parser.add_argument("--model-path", default=str(DEFAULT_MODEL_PATH))
    parser.add_argument("--test-data-path", default=str(DEFAULT_TEST_DATA_PATH))
    parser.add_argument("--report-path", default=str(DEFAULT_REPORT_PATH))
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = parse_args()
    run_evaluation(args.model_path, args.test_data_path, args.report_path)
